# Generated by Django 3.2.9 on 2021-11-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='actvity',
            new_name='activity',
        ),
    ]
